apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-app-deployment
  namespace: dev
  labels:
    app: iot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-app
  template:
    metadata:
      labels:
        app: iot-app
    spec:
      containers:
      - name: iot-app
        image: nmartindock/iot-app:v1
        ports:
        - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: iot-app-service
  namespace: dev
spec:
  selector:
    app: iot-app
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iot-app-ingress
  namespace: dev
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: iot-app-service
            port:
              number: 8888